inherits = "dracutux"

[palette]
base = "#eeeeff"
ui_base = "#ffffff"

text = "#444433"
subtle_text = "#777788"

selection = "#ddccff"
ui_selection = "#ccccdd"

comment = "#aabbee"

cyan = "#448899"
blue = "#4477cc"

green = "#33aa55"
teal = "#339977"

pink = "#bb5588"

purple = "#7744bb"

red = "#ee4444"

yellow = "#778822"
orange = "#aa6633"
